export enum AiKnowledgeModule {
  RIDE = "Ride",
  WALLET = "Wallet",
  REFERRAL = "Referral",
  TIER = "Tier",
  POINTS = "Points",
  DESTINATION_FILTER = "Destination Filter",
  LOST_FOUND = "Lost Found",
  SUPPORT = "Support",
  FAQ = "FAQ",
  DOCUMENTS = "Documents",
  ACCOUNT = "Account",
  VEHICLE = "Vehicle",
  SAFETY = "Safety",
  CANCELLATION = "Cancellation",
  RATINGS = "Ratings",
  COMPLIANCE = "Compliance",
  FARES = "Fares",
  SERVICE_AREA = "Service Area",
}

export enum AiKnowledgeCategory {
  GENERAL = "general",
  PAYMENT = "payment",
  POLICY = "policy",
  REWARDS = "rewards",
  VERIFICATION = "verification",
  GUIDELINES = "guidelines",
  SAFETY = "safety",
  FARES = "fares",
  TROUBLESHOOTING = "troubleshooting",
  FAQ = "faq",
}

export enum AiKnowledgeTag {
  DRIVER = "driver",
  PASSENGER = "passenger",
  PAYOUT = "payout",
  BOOKING = "booking",
  CANCELLATION = "cancellation",
  REGISTRATION = "registration",
  DOCUMENT_UPLOAD = "document_upload",
  HELP = "help",
  RULES = "rules",
  PROMO = "promo",
  SECURITY = "security",
  EMERGENCY = "emergency",
  VEHICLE_APPROVAL = "vehicle_approval",
  IMPORTED = "imported",
  MARKDOWN = "markdown",
}